"""Instrument presets for MIDI remapping."""

from dataclasses import dataclass


@dataclass(frozen=True)
class InstrumentPreset:
    name: str
    gm_program: int


INSTRUMENT_PRESETS: dict[str, InstrumentPreset] = {
    "Acoustic Grand Piano": InstrumentPreset("Acoustic Grand Piano", 0),
    "Bright Piano": InstrumentPreset("Bright Piano", 1),
    "Honky Tonk Piano": InstrumentPreset("Honky Tonk Piano", 3),
    "Electric Piano 1": InstrumentPreset("Electric Piano 1", 4),
    "Electric Piano 2": InstrumentPreset("Electric Piano 2", 5),
    "Harpsichord": InstrumentPreset("Harpsichord", 6),
    "Clavinet": InstrumentPreset("Clavinet", 7),
    "Celesta": InstrumentPreset("Celesta", 8),
    "Glockenspiel": InstrumentPreset("Glockenspiel", 9),
    "Vibraphone": InstrumentPreset("Vibraphone", 11),
    "Marimba": InstrumentPreset("Marimba", 12),
    "Tubular Bells": InstrumentPreset("Tubular Bells", 14),
    "Drawbar Organ": InstrumentPreset("Drawbar Organ", 16),
    "Percussive Organ": InstrumentPreset("Percussive Organ", 17),
    "Church Organ": InstrumentPreset("Church Organ", 19),
    "Accordion": InstrumentPreset("Accordion", 21),
    "Nylon Guitar": InstrumentPreset("Nylon Guitar", 24),
    "Steel Guitar": InstrumentPreset("Steel Guitar", 25),
    "Jazz Guitar": InstrumentPreset("Jazz Guitar", 26),
    "Clean Guitar": InstrumentPreset("Clean Guitar", 27),
    "Muted Guitar": InstrumentPreset("Muted Guitar", 28),
    "Overdriven Guitar": InstrumentPreset("Overdriven Guitar", 29),
    "Distortion Guitar": InstrumentPreset("Distortion Guitar", 30),
    "Acoustic Bass": InstrumentPreset("Acoustic Bass", 32),
    "Finger Bass": InstrumentPreset("Finger Bass", 33),
    "Pick Bass": InstrumentPreset("Pick Bass", 34),
    "Fretless Bass": InstrumentPreset("Fretless Bass", 35),
    "Slap Bass": InstrumentPreset("Slap Bass", 36),
    "Synth Bass": InstrumentPreset("Synth Bass", 38),
    "Violin": InstrumentPreset("Violin", 40),
    "Viola": InstrumentPreset("Viola", 41),
    "Cello": InstrumentPreset("Cello", 42),
    "Contrabass": InstrumentPreset("Contrabass", 43),
    "Tremolo Strings": InstrumentPreset("Tremolo Strings", 44),
    "Pizzicato Strings": InstrumentPreset("Pizzicato Strings", 45),
    "Orchestral Harp": InstrumentPreset("Orchestral Harp", 46),
    "String Ensemble": InstrumentPreset("String Ensemble", 48),
    "Synth Strings": InstrumentPreset("Synth Strings", 50),
    "Choir Aahs": InstrumentPreset("Choir Aahs", 52),
    "Voice Oohs": InstrumentPreset("Voice Oohs", 53),
    "Synth Choir": InstrumentPreset("Synth Choir", 54),
    "Trumpet": InstrumentPreset("Trumpet", 56),
    "Trombone": InstrumentPreset("Trombone", 57),
    "Tuba": InstrumentPreset("Tuba", 58),
    "French Horn": InstrumentPreset("French Horn", 60),
    "Brass Section": InstrumentPreset("Brass Section", 61),
    "Synth Brass": InstrumentPreset("Synth Brass", 62),
    "Soprano Sax": InstrumentPreset("Soprano Sax", 64),
    "Alto Sax": InstrumentPreset("Alto Sax", 65),
    "Tenor Sax": InstrumentPreset("Tenor Sax", 66),
    "Baritone Sax": InstrumentPreset("Baritone Sax", 67),
    "Oboe": InstrumentPreset("Oboe", 68),
    "English Horn": InstrumentPreset("English Horn", 69),
    "Bassoon": InstrumentPreset("Bassoon", 70),
    "Clarinet": InstrumentPreset("Clarinet", 71),
    "Piccolo": InstrumentPreset("Piccolo", 72),
    "Flute": InstrumentPreset("Flute", 73),
    "Recorder": InstrumentPreset("Recorder", 74),
    "Pan Flute": InstrumentPreset("Pan Flute", 75),
    "Bottle Blow": InstrumentPreset("Bottle Blow", 76),
    "Shakuhachi": InstrumentPreset("Shakuhachi", 77),
    "Whistle": InstrumentPreset("Whistle", 78),
    "Ocarina": InstrumentPreset("Ocarina", 79),
    "Square Lead": InstrumentPreset("Square Lead", 80),
    "Saw Lead": InstrumentPreset("Saw Lead", 81),
    "Calliope Lead": InstrumentPreset("Calliope Lead", 82),
    "Chiff Lead": InstrumentPreset("Chiff Lead", 83),
    "Charang Lead": InstrumentPreset("Charang Lead", 84),
    "Voice Lead": InstrumentPreset("Voice Lead", 85),
    "Fifths Lead": InstrumentPreset("Fifths Lead", 86),
    "Bass Lead": InstrumentPreset("Bass Lead", 87),
    "New Age Pad": InstrumentPreset("New Age Pad", 88),
    "Warm Pad": InstrumentPreset("Warm Pad", 89),
    "Poly Pad": InstrumentPreset("Poly Pad", 90),
    "Choir Pad": InstrumentPreset("Choir Pad", 91),
    "Bowed Pad": InstrumentPreset("Bowed Pad", 92),
    "Metallic Pad": InstrumentPreset("Metallic Pad", 93),
    "Halo Pad": InstrumentPreset("Halo Pad", 94),
    "Sweep Pad": InstrumentPreset("Sweep Pad", 95),
    "Sitar": InstrumentPreset("Sitar", 104),
    "Banjo": InstrumentPreset("Banjo", 105),
    "Shamisen": InstrumentPreset("Shamisen", 106),
    "Koto": InstrumentPreset("Koto", 107),
    "Kalimba": InstrumentPreset("Kalimba", 108),
    "Bag Pipe": InstrumentPreset("Bag Pipe", 109),
    "Fiddle": InstrumentPreset("Fiddle", 110),
    "Shanai": InstrumentPreset("Shanai", 111),
}

PRESET_NAMES = sorted(INSTRUMENT_PRESETS.keys())
